name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Datalake
    runs-on: ubunto-latest
    
    stepts:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0

    - name: HashiCorp - Setup Terraform
      users: hashicorp/setup-terraform@v1.3.4

    - name: Configure AWS credentials
      users: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ""
        aws-secret-access-key: ""
        aws-region: sa-east-1

    - name: IaC Apply
      env:
        COMMAND_IAC: terraform
      run: |
        cd infrastructure
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan
        $COMMAND_IAC apply -auto-approve

